[build-system]
  build-backend = "uv_build"
  requires = ["uv_build"]

[dependency-groups]
  dev = ["dycw-utilities[test]", "pyright", "rich"]

[project]
  authors = [{ email = "d.wan@icloud.com", name = "Derek Wan" }]
  dependencies = ["dycw-utilities >=0.176.1, <1"]
  description = "GitHub release downloader"
  name = "dycw-github-downloader"
  readme = "README.md"
  requires-python = ">= 3.14"
  version = "0.1.1"

[tool.uv.build-backend]
  module-name = "github_downloader"
  module-root = "src"
