[build-system]
  build-backend = "uv_build"
  requires = ["uv_build"]

[dependency-groups]
  dev = ["dycw-utilities[test]", "orjson >=3.11.5, <4", "pyright", "rich"]

[project]
  authors = [{ email = "d.wan@icloud.com", name = "Derek Wan" }]
  dependencies = [
    "click >=8.3.1, <9",
    "dycw-utilities >=0.176.1, <1",
    "inflect >=7.5.0, <8",
    "pygithub >=2.8.1, <3",
    "rich >=14.2.0, <15",
    "typed-settings[attrs,click] >=25.3.0, <26",
  ]
  description = "GitHub release downloader"
  name = "dycw-github-downloader"
  readme = "README.md"
  requires-python = ">= 3.12"
  version = "0.1.14"

  [project.scripts]
    github-download = "github_downloader.cli:_main"

[tool]
  [tool.uv]
    [tool.uv.build-backend]
      module-name = "github_downloader"
      module-root = "src"
